# Generated by Django 2.2.10 on 2020-05-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cases', models.CharField(max_length=120)),
                ('deaths', models.CharField(max_length=120)),
                ('recovered', models.CharField(max_length=120)),
                ('tests', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cases', models.CharField(max_length=120)),
                ('total_deaths', models.CharField(max_length=120)),
                ('total_recovered', models.CharField(max_length=120)),
            ],
        ),
    ]
